# Generated by Django 5.2.8 on 2025-11-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descreptions',
        ),
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
